package com.geeksville.apiproxy

import java.net.Socket
import java.net.InetSocketAddress
import java.io.BufferedOutputStream
import com.geeksville.dapi._
import com.google.protobuf.ByteString

class GCSHooksImpl(host: String = APIConstants.DEFAULT_SERVER, port: Int = APIConstants.DEFAULT_TCP_PORT) extends GCSHooks {
  private val socket = new Socket();
  socket.setTcpNoDelay(true); // Turn off nagle
  socket.connect(new InetSocketAddress(host, port))

  private val out = new BufferedOutputStream(socket.getOutputStream(), 8192)
  private val in = socket.getInputStream()

  private val startTime = System.currentTimeMillis * 1000L

  /**
   * GCS must call this for ever mavlink packet received or sent from the
   * vehicle
   *
   * @param bytes
   *            the packet
   * @param fromInterface
   *            the interface # this data arrived on (or -1 if generated by
   *            the GCS itself)
   * @throws IOException
   */
  def filterMavlink(fromInterface: Int, bytes: Array[Byte]) {
    val deltat = (System.currentTimeMillis() * 1000) - startTime

    Envelope(mavlink = Some(MavlinkMsg(fromInterface, Vector(ByteString.copyFrom(bytes)), Some(deltat)))).writeDelimitedTo(out)
  }

  /**
   * Connect to web service
   *
   * @param userName
   * @param password
   * @throws IOException
   * @throws UnknownHostException
   */
  def loginUser(userName: String, password: String) {
    Envelope(login = Some(LoginMsg(userName, password, Some(startTime)))).writeDelimitedTo(out)
  }

  /**
   * Associate a server vehicleId string with a particular mavlink sysId. GCS
   * must call this for every vehicle that is connected.
   *
   * @param vehicleId
   *            a UUID for this vehicle, if the server has never seen this
   *            UUID before, a new vehicle record will be created. Use the
   *            special string "gcs" for data from the GCS (not really a
   *            vehicle)
   * @param fromInterface
   *            the interface # this vehicle is connected on
   * @param mavlinkSysId
   *            the mavlink sysid for this vehicle
   * @throws IOException
   */
  def setVehicleId(vehicleId: String, fromInterface: Int, mavlinkSysId: Int) {
    Envelope(setVehicle = Some(SetVehicleMsg(fromInterface, mavlinkSysId, vehicleId, false))).writeDelimitedTo(out)
  }

  /**
   * Send any queued messages immedately
   */
  def flush() {
    out.flush()
  }

  /**
   * Disconnects from web service
   */
  def close() {
    out.close()
    in.close()
    socket.close()
  }
}