// Generated by CoffeeScript 1.6.3
(function() {
  var alertFail, alertSuccess, failMessage, goodMessage;

  goodMessage = function(str) {
    return '&#x2713; ' + str;
  };

  failMessage = function(str) {
    return '&#x2717; ' + str;
  };

  alertSuccess = function(str) {
    return "<div class='alert alert-success'>" + goodMessage(str) + "</div>";
  };

  alertFail = function(str) {
    return "<div class='alert alert-danger'>" + failMessage(str) + "</div>";
  };

  new GCSAPI.View.VehicleBased({
    el: '#telem-connected',
    watching: 'has_heartbeat',
    getContent: function() {
      var msg;
      return msg = this.model.has_heartbeat() ? alertSuccess('Telemetry connected') : alertFail('Vehicle not connected');
    }
  });

  new GCSAPI.View.VehicleBased({
    el: '#rc-connected',
    watching: 'rc_connected',
    getContent: function() {
      var msg;
      return msg = this.model.rc_connected() ? alertSuccess('RC Transmitter is on') : alertFail('RC Transmitter offline');
    }
  });

  new GCSAPI.View.VehicleBased({
    el: '#manual-mode',
    watching: 'manual_mode',
    getContent: function() {
      var mode, msg;
      mode = this.model.current_mode();
      return msg = (mode === "MANUAL") || (mode === "STABILIZE") ? alertSuccess('Vehicle in MANUAL mode') : alertFail('Vehicle not in MANUAL mode');
    }
  });

  new GCSAPI.View.VehicleBased({
    el: '#has-3d-fix',
    watching: 'location',
    getContent: function() {
      var msg;
      return msg = this.model.has_3d_fix() ? alertSuccess('GPS has 3D fix') : alertFail('GPS does not have 3D fix');
    }
  });

}).call(this);
